pipeline
{
  agent any

  stages
  {
    stage('build')
    {
      steps{
        echo "Building the application..."
      }
    }

    stage('test')
    {
      steps{
        echo "Testing the application..."
      }
    }

    stage('deploy')
    {
      steps{
      echo "Deploying the application..." 
      }
    }
  }
}



















// pipeline
// {

// agent {
//   label 'DevServer'
// }

// tools {
//   maven 'mymaven'
// }

// stages{

//     stage('build')
//     {
//         steps {
//             sh 'mvn clean package'
//         }

//         post {
//         success {
//             archiveArtifacts artifacts: '**/target/*.war'
//                  }
//             }

//     }

   

    
// }

// }